### ISSUE TITLE
Link na kroužek

### ISSUE THREAD

**Issue by martinnpuk** [Delta-Krouzek/11_hodina_TowerDefense#1]
Zdravím, už jsem psal mail ale asi jste nedostali upozornění. Nemám jak vás jinak kontaktovat tak píšu sem. Prostě potřebuju link na kroužek heeh díky @czM1K3 @kahy9

**Comment by czM1K3** [comment]
https://teams.microsoft.com/l/meetup-join/19%3Ameeting_ZGY1M2JiYjgtZDVmNi00ODFhLTkzYjgtNzcxNDE5OTNjZTlk%40thread.v2/0?context=%7B%22Tid%22%3A%2281d89366-7747-4fe5-a737-97f57d0c18ec%22%2C%22Oid%22%3A%22c5cda95d-4eb9-4a28-a69f-5a854409f061%22%2C%22MessageId%22%3A%220%22%7D
